### ISSUE TITLE
Error in get_pkg_srcrefs(pkg) : Unexpected format for source refs.

### ISSUE THREAD

**Issue by caseybreen** [r-lib/profvis#134]
I'm getting an error when I try to profile code with RStudio (following this [tutorial](https://support.rstudio.com/hc/en-us/articles/218221837-Profiling-R-code-with-the-RStudio-IDE)). 

Here's a reprex: 

```
profvis({
     data(diamonds, package = "ggplot2") 
     plot(price ~ carat, data = diamonds)
     m <- lm(price ~ carat, data = diamonds)
     abline(m, col = "red")
 })

Error in get_pkg_srcrefs(pkg) : Unexpected format for source refs.
```

Thanks!

**Comment by gcpoole** [comment]
I was getting this same message.  It happened when I was using devtools::load_all(".") while building a package.  This makes sense because the package I was working on was not in sync with the most recently built version.  When I properly built the package (install and restart under build menu in RStudio), the error was resolved.  

Perhaps profvis could somehow check to be sure that loaded version is that same as the most recent build and throw a friendlier error?

**Comment by hadley** [comment]
I haven't seen this problem for a while, so I'm going to assume it's fixed. Please let me know if you see it again and I'll investigate further.

**Comment by hongyuanjia** [comment]
@hadley I still see this problem when a package contains a function created using `checkmate::makeTestFunction()`. `checkmate::makeTestFunction()` creates a new function based on the input function.

Below is a MRE:

1. First create a package using {usethis}
```r
usethis::create_package("profvis.test")
```

2. Create an R file containing functions created using `checkmate::makeTestFunction()`.
```r
writeLines(
"check_same_len <- function(x, y) {
    if (NROW(x) == NROW(y)) TRUE else \"Must have same length\"
}
test_same_len <- checkmate::makeTestFunction(check_same_len)"
,
    "R/check.R"
)
```

3. Load the package using `devtools::load_all()` and run profvis:
```r
devtools::load_all()
profvis::profvis(test_same_len(mtcars, mtcars))
#> Error in get_pkg_srcrefs(pkg) : Unexpected format for source refs.
```

Digging a little bit deeper, I found that this error is caused by `file_contents.R#L113`

https://github.com/r-lib/profvis/blob/dec7381a90aac83e534a1e9f1c85a8874989862b/R/file_contents.R#L113

`utils::getSrcref(x)` returns a list of two elements instead of one:
```r
[[1]]
{

[[2]]
isTRUE(check_same_len(x, y))
```

Thus `srcfile <- attr(srcref, "srcfile", exact = TRUE)` will always return `NULL` in this case.

**Comment by hadley** [comment]
Thanks for the reprex, but it works for me 😞 (once I add a `Sys.sleep()` to `check_same_len()` so it doesn't run too quickly to profile).

**Comment by hadley** [comment]
What version of R are you using? 

Does it reproduce for you with this simpler test case?

```R
check_same_len <- function(x, y) {
  if (NROW(x) == NROW(y)) TRUE else "Must have same length"
}
test_same_len <- checkmate::makeTestFunction(check_same_len)
profvis::profvis(test_same_len(mtcars, mtcars))
```

It's possible due to the line `body(new.fun) = parse(text = paste("{", body, "}"))` in `checkmate::makeTestFunction()`. `parse()` returns an expression-list, but a function body should be a call. It's possible a more recent version of R handles this automatically so I don't see the problem.

**Comment by hongyuanjia** [comment]
I'm using R 4.4.0. You are right. The `body` part is the root cause. 

Interesting. It also works fine for me inside R scripts. This error only occurs when using makeTestFunction inside a package and loading it using devtools.

**Comment by gcpoole** [comment]
@hongyuanjia, this is consistent with the behavior I experienced, described in my May 10, 2022 post.  I only experienced the error when using devtools to load a package during development.  When I built the package, without modifying the code, and loaded the package, profvis worked just fine

**Comment by olivroy** [comment]
I see this in RStudio in pkg dev with R 4.4.1 only when I have breakpoints set (via RStudio UI). I don't get the error if I clear all breakpoints
